apiVersion: v1
kind: Service
metadata:
  labels:
    app: final-project-svc
  name: final-project-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: final-project
